### PR TITLE
Add new spinner "The Irish"

### PR DESCRIPTION
**Pull request by sebmck**
This PR adds a new spinner called "The Irish". Along with this patch comes the ability to specify custom music and background for a spinner.

The Irish is a premium spinner that features a dog background and a looped 10 second clip of the cult classic "Hamster Dance".

screen shot 2017-06-07 at 5 43 56 pm

screen shot 2017-06-07 at 5 44 53 pm

### CODE REVIEW

**Comment by samccone** [comment]
Audio seems to be not playing on Android. 
Also can you compress your images?

**Comment by kittens** [comment]
Compressed the images and audio.

**Comment by austinkelleher** [comment]
I've been waiting for this change. Thanks for getting around to implementing it.

**Comment by jeffijoe** [comment]
I'm sure the stakeholders will be pleased.

**Comment by samccone** [comment]
* [ ] Need to hook audioplayback through our ac context, so that the global mute will work.

**Comment by sebmck** [comment]
Bump please merge

**Comment by samccone** [comment]
can you reopen please!

**Comment by sebmck** [comment]
I refuse. I have never been treated so poorly as a contributor. Shame on you.

**Pull request closed without merging**
